/**
 * Comprehensive list of known exercises across all muscle groups.
 */
export const KNOWN_EXERCISES: string[] = [
  // Chest
  'Barbell Bench Press',
  'Cable Crossover',
  'Chest Dips',
  'Decline Barbell Bench Press',
  'Decline Dumbbell Press',
  'Dumbbell Fly',
  'Flat Dumbbell Press',
  'Incline Barbell Bench Press',
  'Incline Dumbbell Fly',
  'Incline Dumbbell Press',
  'Machine Chest Press',
  'Pec Deck Fly',
  'Push-ups',

  // Back
  'Back Extension',
  'Barbell Deadlift',
  'Barbell Row',
  'Barbell Shrug',
  'Chest-Supported Row',
  'Chin-ups',
  'Close-Grip Lat Pulldown',
  'Dumbbell Shrug',
  'Face Pull',
  'Lat Pulldown',
  'Pendlay Row',
  'Pull-ups',
  'Romanian Deadlift',
  'Seated Cable Row',
  'Single-Arm Dumbbell Row',
  'Straight-Arm Cable Pulldown',
  'Sumo Deadlift',
  'T-Bar Row',

  // Shoulders
  'Arnold Press',
  'Cable Lateral Raises',
  'Front Dumbbell Raise',
  'Lateral Raises',
  'Machine Shoulder Press',
  'Overhead Press',
  'Push Press',
  'Rear Delt Dumbbell Fly',
  'Reverse Pec Deck',
  'Seated Dumbbell Shoulder Press',
  'Upright Row',

  // Legs (Quads, Hamstrings, Glutes, Calves)
  'Abductor Machine',
  'Adductor Machine',
  'Barbell Squat',
  'Bulgarian Split Squat',
  'Calf Raise',
  'Front Squat',
  'Goblet Squat',
  'Hack Squat',
  'Hip Thrust',
  'Leg Curl',
  'Leg Extension',
  'Leg Press',
  'Lying Leg Curl',
  'Reverse Lunges',
  'Seated Calf Raise',
  'Seated Leg Curl',
  'Standing Calf Raise',
  'Stiff-Legged Deadlift',
  'Walking Lunges',

  // Arms (Biceps, Triceps, Forearms)
  'Barbell Curl',
  'Bicep Curl',
  'Cable Curl',
  'Cable Overhead Tricep Extension',
  'Close-Grip Bench Press',
  'Concentration Curl',
  'Diamond Push-ups',
  'Hammer Curl',
  'Incline Dumbbell Curl',
  'Overhead Tricep Extension',
  'Preacher Curl',
  'Reverse Wrist Curl',
  'Skull Crushers',
  'Tricep Dips',
  'Tricep Pushdown',
  'Wrist Curl',

  // Core / Abs
  'Ab Wheel Rollout',
  'Cable Crunch',
  'Cable Woodchopper',
  'Decline Crunch',
  'Hanging Knee Raise',
  'Hanging Leg Raise',
  'Plank',
  'Russian Twist',
];
